// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpTA1VoWLS-iCK4Ahko7Gpx0Q13NTnVgk',
    appId: '1:752410586008:web:9642f3d8a1f70953ecd9ed',
    messagingSenderId: '752410586008',
    projectId: 'apfsvalencia',
    authDomain: 'apfsvalencia.firebaseapp.com',
    databaseURL: 'https://apfsvalencia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'apfsvalencia.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCirGQDgW4zFv6aOQokFpu2MqbczO3fAZk',
    appId: '1:752410586008:android:b1eae150883a01c5ecd9ed',
    messagingSenderId: '752410586008',
    projectId: 'apfsvalencia',
    databaseURL: 'https://apfsvalencia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'apfsvalencia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUEXS11mbOE2le407cARhOPxOxIX_S_So',
    appId: '1:752410586008:ios:32e29c952d09ccd9ecd9ed',
    messagingSenderId: '752410586008',
    projectId: 'apfsvalencia',
    databaseURL: 'https://apfsvalencia-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'apfsvalencia.appspot.com',
    iosClientId: '752410586008-suorkf83rumm6ot73ffi5eufl99k2lkq.apps.googleusercontent.com',
    iosBundleId: 'com.example.apfsvalencia',
  );
}
